version: '3'

services:
  db:
    image: mysql #:8
    ports:
      - ${DB_EXPOSED_PORT-3306}:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=social_network
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: docker.io/bitnami/laravel:8
    ports:
      - ${APP_EXPOSED_PORT-8000}:8000
    environment:
      - APP_NAME=SocialNetwork
      - APP_ENV=local
      - APP_KEY=base64:i+33sCHNatChtMg5HdIKh7gMvyJaSvGJ+qNjpJm0AUg=
      - APP_DEBUG=true
      - APP_URL=//localhost:${APP_EXPOSED_PORT-8000}

      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=social_network
      - DB_USERNAME=app
      - DB_PASSWORD=app

      - SESSION_DRIVER=cookie
      - SESSION_LIFETIME=120
      - SESSION_DOMAIN=.localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:${APP_EXPOSED_PORT-8000}

      # - MAIL_MAILER=smtp
      # - MAIL_HOST=smtp.gmail.com
      # - MAIL_PORT=587
      # - MAIL_USERNAME=
      # - MAIL_PASSWORD=
      # - MAIL_ENCRYPTION=tls
      # - MAIL_FROM_ADDRESS=
      # - MAIL_FROM_NAME="${APP_NAME}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - php_vendor:/app/vendor
    depends_on:
      - db
    command: /app/run.sh
volumes:
  db_data:
  node_modules:
  php_vendor:
